language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

install:
  - pip install pep8
  - pip install --upgrade pyflakes
  - pip install unittest2
  - pip install coveralls

before_script:
 - pep8 *.py */*.py --ignore=E501,W601
  # to have the list anyway
 - pep8 *.py */*.py --select=E501,W601 || true

script:
 - coverage run -m unittest2.__main__ discover --start-directory=didyoumean --pattern=*.py

after_success:
  coveralls
