language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5-dev"
  - "3.5.0b2"
  - "3.5.0b3"
  - "nightly"
  - "pypy"
  - "pypy3"

install:
  - pip install --upgrade pep8
  - pip install pep257
  - pip install --upgrade pyflakes
  - pip install unittest2
  - pip install coverage==3.7.1 # https://bitbucket.org/ned/coveragepy/issues/407/coverage-failing-on-python-325-using
  - pip install coveralls
  - pip install codecov

before_script:
 - pep8 *.py */*.py
 - pep257 *.py */*.py

script:
 - if [ "$TRAVIS_PYTHON_VERSION" != "nightly" ]; then coverage run -m unittest2.__main__ discover --start-directory=didyoumean --pattern=*.py; fi
 - if [ "$TRAVIS_PYTHON_VERSION" == "nightly" ]; then       python -m unittest2.__main__ discover --start-directory=didyoumean --pattern=*.py; fi
 - python didyoumean/readme_examples.py

after_success:
 - coveralls
 - codecov
