language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

install:
  - pip install pep8
  - pip install --upgrade pyflakes

before_script:
 - pep8 *.py */*.py --ignore=E501
  # to have the list anyway
 - pep8 *.py */*.py --select=E501 || true

script:
 - python -m unittest discover --start-directory=didyoumean --pattern=*.py
