language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"
  - "pypy"
  - "pypy3"

install:
  - pip install pep8
  - pip install --upgrade pyflakes
  - pip install unittest2
  - pip install coveralls

before_script:
 - pep8 *.py */*.py

script:
 - coverage run -m unittest2.__main__ discover --start-directory=didyoumean --pattern=*.py

after_success:
  coveralls
