language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "3.5.0b2"
  - "3.5.0b3"
  - "3.6-dev"
  - "nightly"
  - "pypy531"
  - "pypy541"
  - "pypy560"
  - "pypy3"

matrix:
  allow_failures:
  - python: pypy531
  - python: pypy541
  - python: pypy560

install:
  # From https://github.com/frol/flask-restplus-server-example/blob/master/.travis.yml
  # Travis has pypy 2.5.0, which is way too old, so we upgrade it on the fly:
  - |
      if [ "$TRAVIS_PYTHON_VERSION" = "pypy531" ] ||
         [ "$TRAVIS_PYTHON_VERSION" = "pypy541" ] ||
         [ "$TRAVIS_PYTHON_VERSION" = "pypy560" ]; then
        export PYENV_ROOT="$HOME/.pyenv"
        if [ -f "$PYENV_ROOT/bin/pyenv" ]; then
          pushd "$PYENV_ROOT" && git pull && popd
        else
          rm -rf "$PYENV_ROOT" && git clone --depth 1 https://github.com/yyuu/pyenv.git "$PYENV_ROOT"
        fi
        case "$TRAVIS_PYTHON_VERSION" in
            "pypy531") export PYPY_VERSION="5.3.1";
            "pypy541") export PYPY_VERSION="5.4.1";
            "pypy560") export PYPY_VERSION="5.6.0";
        esac
        "$PYENV_ROOT/bin/pyenv" install --skip-existing "pypy-$PYPY_VERSION"
        virtualenv --python="$PYENV_ROOT/versions/pypy-$PYPY_VERSION/bin/python" "$HOME/virtualenvs/pypy-$PYPY_VERSION"
        source "$HOME/virtualenvs/pypy-$PYPY_VERSION/bin/activate"
      fi
  - pip install --upgrade pep8
  - pip install pep257
  - pip install --upgrade pyflakes
  - pip install unittest2
  - pip install coverage==3.7.1 # https://bitbucket.org/ned/coveragepy/issues/407/coverage-failing-on-python-325-using
  - pip install coveralls
  - pip install codecov

before_script:
 - pep8 *.py */*.py
 - pep257 *.py */*.py

script:
 - coverage run -m unittest2 discover --start-directory=didyoumean --pattern=*.py
 - python didyoumean/readme_examples.py

after_success:
 - coveralls
 - codecov
